# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('model', models.CharField(max_length=32)),
                ('hardware', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BussinessLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('bussinesslines', models.ManyToManyField(to='bms.BussinessLine')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='bussiness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.BussinessLine'),
        ),
        migrations.AddField(
            model_name='asset',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.Env'),
        ),
    ]
