# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinessline',
            name='description',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
